name: spacex_launches

description: Do not miss SpaceX launches.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  equatable: ^2.0.2
  flutter_bloc: ^7.0.0
  flutter_local_notifications: ^6.0.0
  flutter_native_timezone: ^1.0.10
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
